# -*- coding: utf-8 -*-
"""NN_comp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWVJU3UzbGiNfiLrSQ5TjccMCdDzPoUW
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adam
import matplotlib.pyplot as plt

# Load dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Flatten images (28x28 -> 784)
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

print(x_train.shape)
print(x_test.shape)

def create_model():

    model = Sequential([
        Dense(128, activation='relu', input_shape=(784,)),
        Dense(10, activation='softmax')
    ])

    return model

optimizers = {
    "SGD": SGD(learning_rate=0.01, momentum=0.9),
    "Adagrad": Adagrad(learning_rate=0.01),
    "RMSprop": RMSprop(learning_rate=0.01),
    "Adam": Adam(learning_rate=0.01)
}

histories = {}

epochs = 20
batch_size = 32

for name, optimizer in optimizers.items():

    print(f"\nTraining using {name}")

    model = create_model()

    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        x_train,
        y_train,
        validation_split=0.2,
        epochs=epochs,
        batch_size=batch_size,
        verbose=1
    )

    histories[name] = history

print("\nFinal Results\n")

for name, history in histories.items():

    print(f"{name}")

    print("Training Accuracy : {:.4f}".format(
        history.history['accuracy'][-1]))

    print("Validation Accuracy : {:.4f}".format(
        history.history['val_accuracy'][-1]))

    print("Training Loss : {:.4f}".format(
        history.history['loss'][-1]))

    print("Validation Loss : {:.4f}".format(
        history.history['val_loss'][-1]))

    print("-"*40)

plt.figure(figsize=(10,6))

for name, history in histories.items():
    plt.plot(history.history['accuracy'], label=name)

plt.title("Training Accuracy vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for name, history in histories.items():
    plt.plot(history.history['val_accuracy'], label=name)

plt.title("Validation Accuracy vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for name, history in histories.items():
    plt.plot(history.history['loss'], label=name)

plt.title("Training Loss vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for name, history in histories.items():
    plt.plot(history.history['val_loss'], label=name)

plt.title("Validation Loss vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

for name, history in histories.items():

    best_acc = max(history.history['val_accuracy'])
    epoch = history.history['val_accuracy'].index(best_acc) + 1

    print(f"{name}:")
    print(f"Best Validation Accuracy = {best_acc:.4f}")
    print(f"Reached at Epoch = {epoch}")
    print()